string: '{

"body":{"policies":[{"detail":{"policyInformation":{"policyType":{"code":"AU","description":"Auto"},"termEffectiveDate":"20180216","termExpirationDate":"20190216","premiumInformation":null,"policyHolders":[{"givenName":"STEPHANIEOHZIFV","middleName":null,"surname":"BLUNTOHZIFV","nameSuffix":null,"dob":"19350204","dlNumber":"OB390442","dlState":"OH"}],"phoneNumbers":null,"fromDate":null,"toDate":null},"subjects":[{"driverSequenceId":"0","givenName":"STEPHANIEOHZIFV","middleName":null,"surname":"BLUNTOHZIFV","nameSuffix":null,"dob":"19350204","ssn":null,"gender":"F","maritalStatus":"W","dlNumber":"OB390442","dlState":"OH","relationToPolicyHolder":{"code":"PP","description":"Primary
        Policyholder"},"relationToInsured":{"code":"I","description":"Insured"},"fromDate":"20180816","toDate":"20190216"}],"carrier":{"financialAMBEST":"99999","name":"INSURANCE
        SERVICES O","ambest":"99999","naic":"00000"},"mailingAddress":{"fromDate":"20180816","toDate":"20190216","street1":"1417
        Ridgecrest Dr","street2":null,"city":"Cincinnati","stateCode":"OH","zip":"45206","countryCode":"US"},"coverages":[{"coverageType":{"code":"BINJ","description":"Bodily
        Injury"},"individualLimitAmount":"10000","occurrenceLimitAmount":"25000","combinedSingleLimitAmount":"0","fromDate":"20180816","toDate":"20190216"},{"coverageType":{"code":"PINJ","description":"Personal
        Injury"},"individualLimitAmount":"25000","occurrenceLimitAmount":"50000","combinedSingleLimitAmount":"0","fromDate":"20180816","toDate":"20190216"}],"vehicles":[{"year":"1991","make":"ACURA","model":"INTEGRA","vin":"C4RV1N3X4MPL30001","classCode":"000000","businessUse":null,"territoryCode":null,"collisionDeductibleAmount":"1000","comprehensiveDeductibleAmount":"500","fromDate":"20180816","toDate":"20190216","collisionIndicator":"N","collisionIndividualLimitAmount":null,"collisionOccurenceLimitAmount":null,"comprehensiveIndicator":"N","comprehensiveIndividualLimitAmount":null,"comprehensiveOccurenceLimitAmount":null,"coverages":[{"coverageType":{"code":"BINJ","description":"Bodily
        Injury"},"individualLimitAmount":"10000","occurrenceLimitAmount":"25000","combinedSingleLimitAmount":"0","fromDate":"20180816","toDate":"20190216"},{"coverageType":{"code":"PINJ","description":"Personal
        Injury"},"individualLimitAmount":"25000","occurrenceLimitAmount":"50000","combinedSingleLimitAmount":"0","fromDate":"20180816","toDate":"20190216"}]}],"garageLocations":null,"financeInformations":null},"history":{"policyInformations":[{"policyType":{"code":"AU","description":"Auto"},"termEffectiveDate":null,"termExpirationDate":null,"premiumInformation":null,"policyHolders":[{"givenName":"STEPHANIEOHZIFV","middleName":null,"surname":"BLUNTOHZIFV","nameSuffix":null,"dob":"19350204","dlNumber":"OB390442","dlState":"OH"}],"phoneNumbers":null,"fromDate":"20170216","toDate":"20180816"}],"subjects":[{"driverSequenceId":"1","givenName":"STEPHANIEOHZIFV","middleName":null,"surname":"BLUNTOHZIFV","nameSuffix":null,"dob":"19350204","ssn":null,"gender":"F","maritalStatus":"W","dlNumber":"OB390442","dlState":"OH","relationToPolicyHolder":{"code":"PP","description":"Primary
        Policyholder"},"relationToInsured":{"code":"I","description":"Insured"},"fromDate":"20180216","toDate":"20180816"},{"driverSequenceId":"1","givenName":"STEPHANIEOHZIFV","middleName":"G","surname":"BLUNTOHZIFV","nameSuffix":null,"dob":"19350204","ssn":null,"gender":"F","maritalStatus":"M","dlNumber":"YB627931","dlState":"OH","relationToPolicyHolder":{"code":"SP","description":"Secondary
        Policyholder"},"relationToInsured":{"code":"S","description":"Spouse"},"fromDate":"20170316","toDate":"20180216"},{"driverSequenceId":"0","givenName":"ANDREWOHZIFV","middleName":"A","surname":"BLUNTOHZIFV","nameSuffix":null,"dob":"19281019","ssn":null,"gender":"M","maritalStatus":"M","dlNumber":"MT216600","dlState":"OH","relationToPolicyHolder":{"code":"PP","description":"Primary
        Policyholder"},"relationToInsured":{"code":"I","description":"Insured"},"fromDate":"20170216","toDate":"20180216"}],"mailingAddresses":[{"fromDate":"20170216","toDate":"20180816","street1":"1816
        Waterford Ln","street2":null,"city":"Cincinnati","stateCode":"OH","zip":"45206","countryCode":"US"}],"coverages":[{"coverageType":{"code":"BINJ","description":"Bodily
        Injury"},"individualLimitAmount":"10000","occurrenceLimitAmount":"25000","combinedSingleLimitAmount":"0","fromDate":"20170216","toDate":"20180816"},{"coverageType":{"code":"PINJ","description":"Personal
        Injury"},"individualLimitAmount":"25000","occurrenceLimitAmount":"50000","combinedSingleLimitAmount":"0","fromDate":"20170216","toDate":"20180816"}],"vehicles":[{"year":"1991","make":"ACURA","model":"INTEGRA","vin":"C4RV1N3X4MPL30001","classCode":"000000","businessUse":null,"territoryCode":null,"collisionDeductibleAmount":"1000","comprehensiveDeductibleAmount":"500","fromDate":"20170216","toDate":"20180816","collisionIndicator":"N","collisionIndividualLimitAmount":null,"collisionOccurenceLimitAmount":null,"comprehensiveIndicator":"N","comprehensiveIndividualLimitAmount":null,"comprehensiveOccurenceLimitAmount":null,"coverages":[{"coverageType":{"code":"BINJ","description":"Bodily
        Injury"},"individualLimitAmount":"10000","occurrenceLimitAmount":"25000","combinedSingleLimitAmount":"0","fromDate":"20170216","toDate":"20180816"},{"coverageType":{"code":"PINJ","description":"Personal
        Injury"},"individualLimitAmount":"25000","occurrenceLimitAmount":"50000","combinedSingleLimitAmount":"0","fromDate":"20170216","toDate":"20180816"}]}],"garageLocations":null,"financeInformations":null,"transactionInformations":[{"transactionType":{"code":"NB","description":"New
        Business"},"effectiveDate":"20170216"},{"transactionType":{"code":"ED","description":"Endorsement"},"effectiveDate":"20170316"},{"transactionType":{"code":"RW","description":"Renewal"},"effectiveDate":"20180216"}]},"policyNumber":"OHVRSK2017112013","policyStatus":"EXPIRED","policyReportedDate":"20180517","inceptionDate":"20170216","lastReportedTermEffectiveDate":"20180216","lastReportedTermExpirationDate":"20190216","numberOfCancellations":"0","numberOfRenewals":"1","cancellationDate":null,"disputeStatement":null,"matchBasisInformation":{"matchScore":"100","searchType":{"code":"P","description":"Person"},"matchReasons":["NAME
        IS IDENTICAL","ADDRESS IS IDENTICAL","ZIP IS IDENTICAL"]}}],"coverageLapseInformation":[{"coverageIntervals":[{"carrier":{"financialAMBEST":"99999","name":"INSURANCE
        SERVICES O","ambest":"99999","naic":null},"startDate":"20170316","endDate":"20190216","numberOfCoverageDays":"702","hasBreakFromPriorCoverage":"NA","numberOfLapseDays":"0"}],"givenName":"StephanieOHZIFV","middleName":null,"surname":"BluntOHZIFV","nameSuffix":null,"inputDriverSequenceNumber":"1","hasPossibleLapse":"N","isCurrentInforceCoverage":"N"}],"customElements":null},"header":{"transactionId":"fd4892a1-660b-4c08-bbf3-d49447ff501b","quoteback":"6556"}}'
    http_version: 
  recorded_at: Wed, 05 Feb 2020 22:25:25 GMT
